collections:
  works:
    output: true
    permalink: /works/:name/
  theater:
    output: true
    permalink: /theater/:name/
  ongoing:
    output: true
    permalink: /ongoing/:name/
  other:
    output: true
    permalink: /other/:name/
  collectives:
    output: true
    permalink: /collectives/:name/

defaults:
  - scope:
      path: ""
      type: "works"
    values:
      layout: "work"
  - scope:
      path: ""
      type: "theater"
    values:
      layout: "theater"
  - scope:
      path: ""
      type: "ongoing"
    values:
      layout: "work"
  - scope:
      path: ""
      type: "other"
    values:
      layout: "other"
  - scope:
      path: ""
      type: "collectives"
    values:
      layout: "collective"

exclude:
  - vendor
  - .bundle
  - Gemfile
  - Gemfile.lock
  - node_modules
